### ISSUE TITLE
GAB Science Lab Website

### ISSUE THREAD

**Issue by mabotn** [intelequia/GAB2017ScienceLab#8]
Hello,

I completed the deployment and scaled the pool to 5 nodes

But unfortunately I can't see my name neither look for my email on search at the Gab Lab website

Anybody else facing a similar issues ?

Link to Gab Lab : https://gablab2017.azurewebsites.net/

**Comment by davidjrh** [comment]
The dashboards are having some issues but I confirm all the data is being processed correctly

**Comment by mabotn** [comment]
Yes I did get my result after trying for many attempts
Thank you
